cache_directory: ~/.depx/cache
cache_enabled: true
cleanup:
  backup_before_clean: true
  cleanup_types:
  - dev
  - cache
  confirm_before_clean: true
  dry_run: true
  size_threshold_mb: 50
export:
  compress_output: false
  default_format: json
  include_metadata: true
  output_directory: ./depx-exports
ignore_directories:
- .git
- .svn
- .hg
- __pycache__
- .pytest_cache
- node_modules
- .venv
- venv
- env
log_level: INFO
scan:
  exclude_patterns: []
  follow_symlinks: false
  include_patterns: []
  max_depth: 5
  parallel: true
  project_types: []
